# docker-compose.yml - Development Environment
version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_CONFIG=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/storyforge
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    depends_on:
      - db
      - redis
    command: python run.py

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=storyforge
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  postgres_data: